# Travis-CI Build for ncoden/libft
# see travis-ci.org for details

language: c

# Build options
script: make

# Dependencies
install :
  - wget "http://www.nasm.us/pub/nasm/releasebuilds/2.11.08/nasm-2.11.08.tar.gz" -O "/tmp/nasm-2.11.08.tar.gz"
  - tar -xvf "/tmp/nasm-2.11.08.tar.gz"
  - cd nasm-2.11.08
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..

# Matrix (2 builds)
os:
  - osx
  - linux

compiler:
  - gcc
  - clang
