# Travis-CI Build for ncoden/libft
# see travis-ci.org for details

language: c

# Build options
os: osx
sudo: false
script: make

# Dependencies
before_install:
  - brew update
  - brew upgrade
install :
  - brew install nasm

# Matrix (2 builds)
compiler:
  - gcc
  - clang
