# Travis-CI Build for ncoden/libft
# see travis-ci.org for details

language: c

# Build options
sudo: false
script: make

# Dependencies
before_install:
  - brew install nasm

# Matrix (4 builds)
compiler:
  - gcc
  - clang

os:
  - linux
  - osx
