# Travis-CI Build for ncoden/libft
# see travis-ci.org for details

language: c

# Build options
script: make
sudo: false

# Matrix (2 builds)
os:
  - osx
  - linux

compiler:
  - gcc
  - clang

# Dependencies
addons:
  apt:
    packages:
    - nasm
