# Travis-CI Build for ncoden/libft
# see travis-ci.org for details

language: c

# Build options
os: osx
script: make

# Dependencies
before_install:
  - sudo brew update
  - sudo brew upgrade
install :
  - sudo brew install nasm

# Matrix (2 builds)
compiler:
  - gcc
  - clang
